# Generated by Django 4.2.20 on 2025-03-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MojaAplikacjaGlowna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
